version: "3"
services:
  go: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./docker_go/Dockerfile
    tty: true # コンテナの永続化
    environment:
      GOPATH: '/go/src'
      GOROOT: '/usr/local/go'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_development'
      MYSQL_HOST: 'db'
      MYSQL_PORT: '3306'
    ports:
      - 8080:8080
    volumes:
      - ./:/go/src/zoom-api # マウントディレクトリ
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    ports:
      - '3306:3306'
    # 記載はしているが基本的に下記は使う予定はない
    volumes:
        #mysql.cnfを反映させるためのディレクトリ
      - ./mysql/conf.d:/etc/mysql/conf.d
        #DBの実体を残したい場合にはコメントアウトを外す
      # - ./mysql/data:/var/lib/mysql
        #MySQL初回起動時に実行するsqlやsh等を渡すためのディレクトリ
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: 'go_development'
      MYSQL_ROOT_HOST: "%"

  ngrok:
    image: wernight/ngrok:latest
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: go:8080
     #NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - go